# -*- coding: utf-8 -*-
"""TASK 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cWS9ttn234VxHMcmu3lf-JpEZ_GLgUp7

*TASK-2*

**BY**-PUSHP CHOUDHARY

**Description:**

---


This task involves using the Pandas
library to manipulate data.

**Responsibility:**

---


Load a CSV file into a Pandas
DataFrame. Perform operations like
filtering data based on conditions, handling
missing values, and calculating summary
statistics.
"""

import pandas as pd

data = pd.read_csv("//content//01.Data Cleaning and Preprocessing.csv") #read csv file
data

type(data) #type of data

data.info() #print the data's information

data.describe() #describe statistical

data =data.drop_duplicates() #drop all the duplicates
data

data.isnull() #true for null false for not null

data.isnull().sum()

data.notnull() #true for not null and false for null

data.isnull().sum().sum() #tells the number of null

data2 = data.fillna(value=0) #fill all the nulls to a value 0
data2

data3  = data.fillna(method="pad") #forward filling

data4= data.fillna(method="bfill") #backward filling

import numpy as np
from scipy import stats

data2.columns #detect the outlier using IQR

data2.drop(["Observation"],axis=1,inplace=True) #droping unwanted column
data.columns

Q1 = data2.quantile(0.25)
Q3 = data2.quantile(0.75)
IQR = Q3 - Q1 #assigning value to IQR
print(IQR)

data2 = data2[~((data2 < (Q1 - 1.5 * IQR)) |(data2 > (Q3 + 1.5 * IQR))).any(axis=1)] #formula for IQL
data2

data2.describe() #describe Statistical